version: '3.5' 

services: 

    backend: 
      image: ex112back
      build: . 
      ports: 
        - 8000:8000
      container_name: ex112back

    frontend:
      image: ex112front
      build: .
      ports:
        - 5000:5000
      container_name: ex112front

