version: '3.5' 

services: 

    backend: 
      image: ex112back
      build: . 
      ports: 
        - 8000:8000
      environment: 
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=hunter2
        - DB_HOST=postgres
      container_name: ex112back
      restart: unless-stopped

    frontend:
      image: ex112front
      build: .
      ports:
        - 5000:5000
      container_name: ex112front

    redis:
      image: redis
      build: .
      ports:
        - 6379:6379
      container_name: redis

    postgres:
      image: postgres
      build: .
      environment:
        - POSTGRES_PASSWORD=hunter2
      container_name: postgres

