FROM alpine
RUN apk add --no-cache python3 python3-pip build-essential libssl-dev libffi-dev python-dev wget curl git vim &&\
    python3 -m pip install --user numpy scipy matplotlib python jupyter pandas sympy nose &&\
    curl https://cli-assets.heroku.com/install.sh | sh &&\
    adduser -D app

USER app

CMD ["/bin/sh"]
